const DemographicsData = {
  USA: {
    country_id: 1,
    country_name: "United States of America",
    country_flag:
      "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/1600px-Flag_of_the_United_States.svg.png",
    country_capital: "Washington, D.C.",
    country_population: 331449281,
    country_world_share: 4.2,
    country_language: ["English"],
    country_timeZones: "UTC−4 to −12, +10, +11",
    country_religions: ["Christianity"],
    country_GDP: "$22.675 trillion",
    country_GDP_perCapita: "$68,309",
    country_currency: "USD",
    country_driving_side: "Right",
    country_calling_code: "+1",
    country_gov_type: "Federal presidential constitutional republic",
  },
  China: {
    country_id: 2,
    country_name: "China",
    country_flag:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.britannica.com%2Ftopic%2Fflag-of-China&psig=AOvVaw0Qd6CKHd76iM1cY48c75kL&ust=1633208820719000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCKjl1o6PqvMCFQAAAAAdAAAAABAD",
    country_capital: "Beijing",
    country_population: 1411778724,
    country_world_share: 18.5,
    country_language: ["Mandarin", "Cantonese", "English"],
    country_timeZones: "UTC+08:00",
    country_religions: ["None", "Buddhism", "Christianity"],
    country_GDP: "$16.64 trillion",
    country_GDP_perCapita: "$11,819",
    country_currency: "CNY",
    country_driving_side: "Right",
    country_calling_code: "+86",
    country_gov_type: "Unitary",
  },
  India: {
    country_id: 3,
    country_name: "India",
    country_flag:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FFlag_of_India&psig=AOvVaw2CGq_nf3Wmz5PAom9yDSmQ&ust=1633209086915000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCMirxI2QqvMCFQAAAAAdAAAAABAR",
    country_capital: "New Delhi",
    country_population: 1352642280,
    country_world_share: 17.7,
    country_language: ["Hindi", "English"],
    country_timeZones: "UTC+05:30",
    country_religions: ["None", "Buddhism", "Christianity"],
    country_GDP: "$3.05 trillion",
    country_GDP_perCapita: "$2,191",
    country_currency: "INR",
    country_driving_side: "Right",
    country_calling_code: "+91",
    country_gov_type: "Federal parliamentary constitutional republic",
  },
};

export default DemographicsData;
