const DemographicsData = {
  NP: {
    country_calling_code: "977",
    country_capital: "Kathmandu",
    country_cities: 6,
    country_currency: "NPR",
    country_demographics_video_src: "https://www.youtube.com/embed/XBqym4HdE8w",
    country_domain: ".np",
    country_flag:
      "https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Nepal.svg",
    country_flag_emoji: "\ud83c\uddf3\ud83c\uddf5",
    country_id: "NP",
    country_income_level: "Lower middle income",
    country_languages: "['Nepali']",
    country_name: "Nepal",
    country_population: 28087871,
    country_states: 19,
  },
  CN: {
    country_calling_code: "86",
    country_capital: "Beijing",
    country_cities: 1716,
    country_currency: "CNY",
    country_demographics_video_src: "https://www.youtube.com/embed/c6cBmZZajyA",
    country_domain: ".cn",
    country_flag:
      "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg",
    country_flag_emoji: "\ud83c\udde8\ud83c\uddf3",
    country_id: "CN",
    country_income_level: "Upper middle income",
    country_languages: "['Chinese']",
    country_name: "China",
    country_population: 1392730000,
    country_states: 34,
  },
  IN: {
    country_calling_code: "91",
    country_capital: "New Delhi",
    country_cities: 1010,
    country_currency: "INR",
    country_demographics_video_src: "https://www.youtube.com/embed/eFCKi5QW1lg",
    country_domain: ".in",
    country_flag:
      "https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg",
    country_flag_emoji: "\ud83c\uddee\ud83c\uddf3",
    country_id: "IN",
    country_income_level: "Lower middle income",
    country_languages: "['English', 'Hindi']",
    country_name: "India",
    country_population: 1352617328,
    country_states: 37,
  },
};

export default DemographicsData;
