image: node:latest

stages:
  - build
  - test
  - deploy

# build_app:
#   stage: build
#   script:
#     - cd front-end
#     - npm install
#     - CI=false npm run-script build

# jest_tests:
#   stage: test
#   script:
#     - cd front-end
#     - npm install
#     - npm test

selenium_tests:
  image: mehuldar/selenium-ci
  stage: test
  script:
    - pip install -r front-end/gui_tests/requirements.txt
    - cd ./front-end
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - apt update -q -y
    - apt --yes install libnss3
    - apt --yes install libgconf-2-4
    - apt --yes install libx11-xcb1
    - apt install -y google-chrome-stable
    # - wget https://chromedriver.storage.googleapis.com/89.0.4389.23/chromedriver_linux64.zip
    # - unzip chromedriver_linux64.zip
    # - cp chromedriver /usr/bin/chromedriver
    # - chown root:root /usr/bin/chromedriver
    # - chmod +x /usr/bin/chromedriver
    # - chmod +x ./chromedriver
    - mount -t tmpfs -o rw,nosuid,nodev,noexec,relatime,size=512M tmpfs /dev/shm
    - python3 gui_tests.py

    - chmod 755 front-end/gui_tests/chromedriver_linux
    - python3 front-end/guitests.py
