image: node:latest

stages:
  - build
  - deploy

build_app:
  stage: build
  script:
    - cd front-end
    - npm install
    - CI=false npm run-script build

deploy_production:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "main"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - git checkout main
  script:
    - cd back-end
    - /root/.local/bin/eb deploy aroundtheworld-api-prod
