image: node:latest

stages:
  - build
  - test
  - deploy

build_app:
  stage: build
  script:
    - cd front-end
    - npm install
    - CI=false npm run-script build

jest_tests:
  stage: test
  script:
    - cd front-end
    - npm install
    - npm test

selenium_tests:
  stage: test
  script:
    - pip install selenium
    - python front-end/guitests.py
