image: node:latest

stages:
  - build
  - test
  - deploy

build_app:
  stage: build
  script:
    - cd front-end
    - npm install
    - CI=false npm run-script build

postman_tests:
  stage: test
  image:
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - newman --version
    - newman run Postman.json
