image: node:latest

stages:
  - build
  - test
  - deploy

# build_app:
#   stage: build
#   script:
#     - cd front-end
#     - npm install
#     - CI=false npm run-script build

# jest_tests:
#   stage: test
#   script:
#     - cd front-end
#     - npm install
#     - npm test

selenium_tests:
  image: mehuldar/selenium-ci
  stage: test
  script:
    - pip install -r front-end/gui_tests/requirements.txt
    - cd ./front-end

    # code from texas votes
    # Dependencies for chromedriver, 
    # https://gist.github.com/mikesmullin/2636776#gistcomment-1742414
    - apt-get update -q -y
    - apt-get install nodejs npm -y
    - apt-get --yes install libnss3
    - apt-get --yes install libgconf-2-4
    - apt-get install libx11-xcb1

    # install chrome and add key
    # based off of
    # - https://gitlab.com/gitlab-org/gitlab-build-images
    # /blob/9dadb28021f15913a49897126a0cd6ab0149e44f/scripts/install-chrome
    # - https://askubuntu.com/a/510186/196148
    - curl -sS -L https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    
    # add repo and install yarn
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ 
      stable main" > /etc/apt/sources.list.d/google.list
    - apt-get update -q -y
    - apt-get install -y google-chrome-stable

    - npm install --global yarn
    - yarn install

    # - apt-get install -y libglib2.0-0 \ libnss3 \ libgconf-2-4 \ libfontconfig1
    # - apt-get install -y chromium-browser
    - chmod 755 front-end/gui_tests/chromedriver_linux
    - python3 front-end/guitests.py
