image: node:latest

stages:
  - build
  - test
  - deploy

build_app:
  stage: build
  script:
    - cd front-end
    - npm install
    - CI=false npm run-script build

postman_tests:
  image: python:3.6-stretch
  stage: test
  image:
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - newman --version
    - newman run Postman.json

unit_tests:
  stage: test
  before_script:
    - pip install -r back-end/requirements.txt
  script:
    - cd back-end
    - python tests.py
