image: node:latest

stages:
  - build
  - test
  - deploy

# build_app:
#   stage: build
#   script:
#     - cd front-end
#     - npm install
#     - CI=false npm run-script build

# jest_tests:
#   stage: test
#   script:
#     - cd front-end
#     - npm install
#     - npm test

selenium_tests:
  image: mehuldar/selenium-ci
  stage: test
  before_script:
    - pip install -r front-end/gui_tests/requirements.txt
    # - apt-get install -y libglib2.0-0 \ libnss3 \ libgconf-2-4 \ libfontconfig1
  script:
    - chmod 755 front-end/gui_tests/chromedriver_linux
    - python front-end/guitests.py
