const GeographyData = {
  Nepal: {
    country_id: 1,
    country_name: "Nepal",
    country_longitude: 84,
    country_latitude: 28,
    country_continent: "Asia",
    country_region: "South Asia",
    country_land_area: "55,348 sq mi",
    country_water_area: "2.6%",
    country_adjacent_oceans: ["None"],
    country_adjacent_countries: { China: "CN", India: "IN" },
  },
  China: {
    country_id: 2,
    country_name: "China",
    country_longitude: 104.1954,
    country_latitude: 35.8617,
    country_continent: "Asia",
    country_region: "East Asia",
    country_land_area: "3,705,407 sq mi",
    country_water_area: "2.8%",
    country_adjacent_oceans: ["Pacific Ocean"],
    country_adjacent_countries: {
      Mongolia: "MN",
      Kazakhstan: "KZ",
      "North Korea": "NK",
      Russia: "RU",
      Kyrgyzstan: "KG",
      Tajikistan: "TJ",
      Afghanistan: "AF",
      Pakistan: "PK",
      India: "IN",
      Nepal: "NP",
      Bhutan: "BT",
      Myanmar: "MM",
      Laos: "LA",
      Vietnam: "VN",
    },
  },
  India: {
    country_id: 3,
    country_name: "India",
    country_longitude: 78.9629,
    country_latitude: 20.5937,
    country_continent: "Asia",
    country_region: "South Asia",
    country_land_area: "1,269,219 sq mi",
    country_water_area: "9.6%",
    country_adjacent_oceans: ["Indian Ocean"],
    country_adjacent_countries: {
      China: "CN",
      Bhutan: "BT",
      Nepal: "NP",
      Pakistan: "PK",
      Bangladesh: "BD",
      Myanmar: "MM",
    },
  },
};

export default GeographyData;
